### ISSUE TITLE
第3章deep-nn的loss在不断降低，但是training_acc一直是0

### ISSUE THREAD

**Issue by lihp11** [L1aoXingyu/code-of-learn-deep-learning-with-pytorch#21]
![image](https://user-images.githubusercontent.com/15975692/43565797-a198dafc-965e-11e8-8979-45fa5be6f133.png)
未发现代码有不对的地方，请求结果的可能解释==

**Comment by L1aoXingyu** [comment]
这是 pytorch 0.4 出来的问题，你把算acc里面的 .data[0] 全部换成 .item() 就可以了
