### ISSUE TITLE
关于Mxtorch

### ISSUE THREAD

**Issue by xiaorannuo** [L1aoXingyu/code-of-learn-deep-learning-with-pytorch#23]
老师你好，我想问一下为什么要写一个Mxtorch呢，我们自己写代码的时候用什么替代呢？

**Comment by L1aoXingyu** [comment]
这个只是模仿一些接口写的，比如keras，目的是为了方便一行训练，因为很多任务中间的forward和backward是一样的，就是这样一个目的，不用也完全没有关系

**Comment by yangyangtiaoguo** [comment]
https://github.com/L1aoXingyu/mxtorch

**Comment by yangyangtiaoguo** [comment]
不用谢

**Comment by w13404457270** [comment]
哪里下载Mxtorch，这个链接https://github.com/L1aoXingyu/mxtorch不对

**Comment by CH-901** [comment]
请问去哪里下载正确的Mxtorch，谢谢

**Comment by L1aoXingyu** [comment]
https://github.com/L1aoXingyu/Deep-Learning-Project-Template/tree/e8733da68124f70a6de06f3027aa111460d57590

**Comment by rainy66alley** [comment]
个人感觉代码写的有些乱， 一种算法，用了好几种方法，而且全部写在一个文档里，为什么不把每种方法写成一个独立完整的程序，对于初学者来说，一点都不方便学习。

**Comment by L1aoXingyu** [comment]
@rainy66alley 你好，你是具体说的那个地方呢？因为我目前正在写1.0版本的书，所以希望收到你的意见，帮助我更好地写好1.0版本

**Comment by jhih-ching-yeh** [comment]
請問一下 Mxtorch 在colab上 要怎麼引進呢？
