### ISSUE TITLE
proper acknowledgement 

### ISSUE THREAD

**Issue by mli** [L1aoXingyu/code-of-learn-deep-learning-with-pytorch#8]
It's great to see a new chinese hands-on book for DL. But I noticed several tutorials are very similar https://github.com/mli/gluon-tutorials-zh. It is often recommended to acknowledge the original author. For example, people often put the following sentence at the beginning or end of the tutorial:

> This tutorial is motivated (or adapted) from xxx

**Comment by SherlockLiao** [comment]
Thanks for your reminders. I am very appreciated for your work about Gluon's hands-on DL book. I wrote the first version of this book in about June last year. Before I prepared the second version, I saw gluon tutorials. That's amazing and awesome. So I drew some lessons from gluon tutorials.
I will put the acknowledge at the end of the first page, and I also hope I can do some help for spreading mxnet gluon.

**Comment by astonzhang** [comment]
Xingyu, thank you for your contributions to open-source communities.

As pointed out by Mu, some notebooks in your repository are very similar to those in Mu's repository (https://github.com/mli/gluon-tutorials-zh), such as

https://github.com/SherlockLiao/code-of-learn-deep-learning-with-pytorch/blob/master/chapter3_NN/optimizer/xxx

https://github.com/SherlockLiao/code-of-learn-deep-learning-with-pytorch/blob/master/chapter4_CNN/yyy

Just for better compliance with the Apache License 2.0 in Mu's repository (https://github.com/mli/gluon-tutorials-zh/blob/master/LICENSE), could you please make the following changes:

1. Include a copy of Apache License 2.0 in your repository. (This may also help protecting your original contents)
2. Add modification notice in each individual file if it is modified from those in Mu's repository.

Thank you again for all your contributions, especially for those to MXNet/Gluon communities :)

**Comment by SherlockLiao** [comment]
Thank you, Aston. I will add this later.
